# Change these first
owner: assia-mz # Your GitHub organization or username, where this repository lives
repo: junior_web_next_upptime # The name of this repository

sites:
  - name: Site — Home
    url: https://junioresiee.com/
    expectedStatusCodes:
      - 200

  - name: Site — Contact
    url: https://junioresiee.com/contact
    expectedStatusCodes:
      - 200

  - name: Site — About
    url: https://junioresiee.com/about
    expectedStatusCodes:
      - 200

  - name: Site — Services
    url: https://junioresiee.com/services
    expectedStatusCodes:
      - 200

  - name: Site — CGU
    url: https://junioresiee.com/terms-of-service
    expectedStatusCodes:
      - 200
  
status-website:
  baseUrl: /junior_web_next_upptime
  name: Junior — Status
  introTitle: ""
  introMessage: ""
  disableCache: true
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://junioresiee.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration


ci:
  node-version: 18
  cache: npm

notifications:
  - type: slack
    webhookUrl: $SLACK_WEBHOOK_URL
    notifyOnStatusChange: true
